//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.LogisticsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogisticsService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Data.DataSet UserLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserLoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyPassword", ReplyAction="http://tempuri.org/IService1/ModifyPasswordResponse")]
        int ModifyPassword(string userName, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyPassword", ReplyAction="http://tempuri.org/IService1/ModifyPasswordResponse")]
        System.Threading.Tasks.Task<int> ModifyPasswordAsync(string userName, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProEngineering", ReplyAction="http://tempuri.org/IService1/AddProEngineeringResponse")]
        int AddProEngineering(string userName, string engineeringName, string uses, string address, string customerName, string customerTel, float price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProEngineering", ReplyAction="http://tempuri.org/IService1/AddProEngineeringResponse")]
        System.Threading.Tasks.Task<int> AddProEngineeringAsync(string userName, string engineeringName, string uses, string address, string customerName, string customerTel, float price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuild", ReplyAction="http://tempuri.org/IService1/GetBuildResponse")]
        System.Data.DataSet GetBuild(string firstLetter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuild", ReplyAction="http://tempuri.org/IService1/GetBuildResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBuildAsync(string firstLetter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProHourse", ReplyAction="http://tempuri.org/IService1/AddProHourseResponse")]
        int AddProHourse(string userName, string machineType, string address, string customerName, string customerTel, float price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProHourse", ReplyAction="http://tempuri.org/IService1/AddProHourseResponse")]
        System.Threading.Tasks.Task<int> AddProHourseAsync(string userName, string machineType, string address, string customerName, string customerTel, float price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Logistics.LogisticsService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Logistics.LogisticsService.IService1>, Logistics.LogisticsService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserLogin(string userName, string password) {
            return base.Channel.UserLogin(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserLoginAsync(string userName, string password) {
            return base.Channel.UserLoginAsync(userName, password);
        }
        
        public int ModifyPassword(string userName, string password, string newPassword) {
            return base.Channel.ModifyPassword(userName, password, newPassword);
        }
        
        public System.Threading.Tasks.Task<int> ModifyPasswordAsync(string userName, string password, string newPassword) {
            return base.Channel.ModifyPasswordAsync(userName, password, newPassword);
        }
        
        public int AddProEngineering(string userName, string engineeringName, string uses, string address, string customerName, string customerTel, float price) {
            return base.Channel.AddProEngineering(userName, engineeringName, uses, address, customerName, customerTel, price);
        }
        
        public System.Threading.Tasks.Task<int> AddProEngineeringAsync(string userName, string engineeringName, string uses, string address, string customerName, string customerTel, float price) {
            return base.Channel.AddProEngineeringAsync(userName, engineeringName, uses, address, customerName, customerTel, price);
        }
        
        public System.Data.DataSet GetBuild(string firstLetter) {
            return base.Channel.GetBuild(firstLetter);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBuildAsync(string firstLetter) {
            return base.Channel.GetBuildAsync(firstLetter);
        }
        
        public int AddProHourse(string userName, string machineType, string address, string customerName, string customerTel, float price) {
            return base.Channel.AddProHourse(userName, machineType, address, customerName, customerTel, price);
        }
        
        public System.Threading.Tasks.Task<int> AddProHourseAsync(string userName, string machineType, string address, string customerName, string customerTel, float price) {
            return base.Channel.AddProHourseAsync(userName, machineType, address, customerName, customerTel, price);
        }
    }
}
