//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.LogisticsService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogisticsService.IService1")]
    public interface IService1 {
        
        // CODEGEN: 参数“UserLoginResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Logistics.LogisticsService.UserLoginResponse UserLogin(Logistics.LogisticsService.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<Logistics.LogisticsService.UserLoginResponse> UserLoginAsync(Logistics.LogisticsService.UserLoginRequest request);
        
        // CODEGEN: 参数“userName”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyPassword", ReplyAction="http://tempuri.org/IService1/ModifyPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Logistics.LogisticsService.ModifyPasswordResponse ModifyPassword(Logistics.LogisticsService.ModifyPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyPassword", ReplyAction="http://tempuri.org/IService1/ModifyPasswordResponse")]
        System.Threading.Tasks.Task<Logistics.LogisticsService.ModifyPasswordResponse> ModifyPasswordAsync(Logistics.LogisticsService.ModifyPasswordRequest request);
        
        // CODEGEN: 参数“userName”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProject", ReplyAction="http://tempuri.org/IService1/AddProjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Logistics.LogisticsService.AddProjectResponse AddProject(Logistics.LogisticsService.AddProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProject", ReplyAction="http://tempuri.org/IService1/AddProjectResponse")]
        System.Threading.Tasks.Task<Logistics.LogisticsService.AddProjectResponse> AddProjectAsync(Logistics.LogisticsService.AddProjectRequest request);
        
        // CODEGEN: 参数“GetBuildResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuild", ReplyAction="http://tempuri.org/IService1/GetBuildResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Logistics.LogisticsService.GetBuildResponse GetBuild(Logistics.LogisticsService.GetBuildRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuild", ReplyAction="http://tempuri.org/IService1/GetBuildResponse")]
        System.Threading.Tasks.Task<Logistics.LogisticsService.GetBuildResponse> GetBuildAsync(Logistics.LogisticsService.GetBuildRequest request);
        
        // CODEGEN: 参数“GetProjectResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProject", ReplyAction="http://tempuri.org/IService1/GetProjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Logistics.LogisticsService.GetProjectResponse GetProject(Logistics.LogisticsService.GetProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProject", ReplyAction="http://tempuri.org/IService1/GetProjectResponse")]
        System.Threading.Tasks.Task<Logistics.LogisticsService.GetProjectResponse> GetProjectAsync(Logistics.LogisticsService.GetProjectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public UserLoginRequest() {
        }
        
        public UserLoginRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet UserLoginResult;
        
        public UserLoginResponse() {
        }
        
        public UserLoginResponse(System.Data.DataSet UserLoginResult) {
            this.UserLoginResult = UserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModifyPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string newPassword;
        
        public ModifyPasswordRequest() {
        }
        
        public ModifyPasswordRequest(string userName, string password, string newPassword) {
            this.userName = userName;
            this.password = password;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyPasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ModifyPasswordResult;
        
        public ModifyPasswordResponse() {
        }
        
        public ModifyPasswordResponse(int ModifyPasswordResult) {
            this.ModifyPasswordResult = ModifyPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddProject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectUses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string machineType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerTel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public float price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectType;
        
        public AddProjectRequest() {
        }
        
        public AddProjectRequest(string userName, string projectName, string projectUses, string machineType, string projectAddress, string customerName, string customerTel, float price, string projectStatus, string projectType) {
            this.userName = userName;
            this.projectName = projectName;
            this.projectUses = projectUses;
            this.machineType = machineType;
            this.projectAddress = projectAddress;
            this.customerName = customerName;
            this.customerTel = customerTel;
            this.price = price;
            this.projectStatus = projectStatus;
            this.projectType = projectType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddProjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AddProjectResult;
        
        public AddProjectResponse() {
        }
        
        public AddProjectResponse(int AddProjectResult) {
            this.AddProjectResult = AddProjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBuild", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBuildRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string firstLetter;
        
        public GetBuildRequest() {
        }
        
        public GetBuildRequest(string firstLetter) {
            this.firstLetter = firstLetter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBuildResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBuildResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetBuildResult;
        
        public GetBuildResponse() {
        }
        
        public GetBuildResponse(System.Data.DataSet GetBuildResult) {
            this.GetBuildResult = GetBuildResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerTel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string machineType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endDate;
        
        public GetProjectRequest() {
        }
        
        public GetProjectRequest(string projectStatus, string customerName, string customerTel, string projectAddress, string projectType, string machineType, string startDate, string endDate) {
            this.projectStatus = projectStatus;
            this.customerName = customerName;
            this.customerTel = customerTel;
            this.projectAddress = projectAddress;
            this.projectType = projectType;
            this.machineType = machineType;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetProjectResult;
        
        public GetProjectResponse() {
        }
        
        public GetProjectResponse(System.Data.DataSet GetProjectResult) {
            this.GetProjectResult = GetProjectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Logistics.LogisticsService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Logistics.LogisticsService.IService1>, Logistics.LogisticsService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logistics.LogisticsService.UserLoginResponse Logistics.LogisticsService.IService1.UserLogin(Logistics.LogisticsService.UserLoginRequest request) {
            return base.Channel.UserLogin(request);
        }
        
        public System.Data.DataSet UserLogin(string userName, string password) {
            Logistics.LogisticsService.UserLoginRequest inValue = new Logistics.LogisticsService.UserLoginRequest();
            inValue.userName = userName;
            inValue.password = password;
            Logistics.LogisticsService.UserLoginResponse retVal = ((Logistics.LogisticsService.IService1)(this)).UserLogin(inValue);
            return retVal.UserLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logistics.LogisticsService.UserLoginResponse> Logistics.LogisticsService.IService1.UserLoginAsync(Logistics.LogisticsService.UserLoginRequest request) {
            return base.Channel.UserLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logistics.LogisticsService.UserLoginResponse> UserLoginAsync(string userName, string password) {
            Logistics.LogisticsService.UserLoginRequest inValue = new Logistics.LogisticsService.UserLoginRequest();
            inValue.userName = userName;
            inValue.password = password;
            return ((Logistics.LogisticsService.IService1)(this)).UserLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logistics.LogisticsService.ModifyPasswordResponse Logistics.LogisticsService.IService1.ModifyPassword(Logistics.LogisticsService.ModifyPasswordRequest request) {
            return base.Channel.ModifyPassword(request);
        }
        
        public int ModifyPassword(string userName, string password, string newPassword) {
            Logistics.LogisticsService.ModifyPasswordRequest inValue = new Logistics.LogisticsService.ModifyPasswordRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.newPassword = newPassword;
            Logistics.LogisticsService.ModifyPasswordResponse retVal = ((Logistics.LogisticsService.IService1)(this)).ModifyPassword(inValue);
            return retVal.ModifyPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logistics.LogisticsService.ModifyPasswordResponse> Logistics.LogisticsService.IService1.ModifyPasswordAsync(Logistics.LogisticsService.ModifyPasswordRequest request) {
            return base.Channel.ModifyPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logistics.LogisticsService.ModifyPasswordResponse> ModifyPasswordAsync(string userName, string password, string newPassword) {
            Logistics.LogisticsService.ModifyPasswordRequest inValue = new Logistics.LogisticsService.ModifyPasswordRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.newPassword = newPassword;
            return ((Logistics.LogisticsService.IService1)(this)).ModifyPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logistics.LogisticsService.AddProjectResponse Logistics.LogisticsService.IService1.AddProject(Logistics.LogisticsService.AddProjectRequest request) {
            return base.Channel.AddProject(request);
        }
        
        public int AddProject(string userName, string projectName, string projectUses, string machineType, string projectAddress, string customerName, string customerTel, float price, string projectStatus, string projectType) {
            Logistics.LogisticsService.AddProjectRequest inValue = new Logistics.LogisticsService.AddProjectRequest();
            inValue.userName = userName;
            inValue.projectName = projectName;
            inValue.projectUses = projectUses;
            inValue.machineType = machineType;
            inValue.projectAddress = projectAddress;
            inValue.customerName = customerName;
            inValue.customerTel = customerTel;
            inValue.price = price;
            inValue.projectStatus = projectStatus;
            inValue.projectType = projectType;
            Logistics.LogisticsService.AddProjectResponse retVal = ((Logistics.LogisticsService.IService1)(this)).AddProject(inValue);
            return retVal.AddProjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logistics.LogisticsService.AddProjectResponse> Logistics.LogisticsService.IService1.AddProjectAsync(Logistics.LogisticsService.AddProjectRequest request) {
            return base.Channel.AddProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logistics.LogisticsService.AddProjectResponse> AddProjectAsync(string userName, string projectName, string projectUses, string machineType, string projectAddress, string customerName, string customerTel, float price, string projectStatus, string projectType) {
            Logistics.LogisticsService.AddProjectRequest inValue = new Logistics.LogisticsService.AddProjectRequest();
            inValue.userName = userName;
            inValue.projectName = projectName;
            inValue.projectUses = projectUses;
            inValue.machineType = machineType;
            inValue.projectAddress = projectAddress;
            inValue.customerName = customerName;
            inValue.customerTel = customerTel;
            inValue.price = price;
            inValue.projectStatus = projectStatus;
            inValue.projectType = projectType;
            return ((Logistics.LogisticsService.IService1)(this)).AddProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logistics.LogisticsService.GetBuildResponse Logistics.LogisticsService.IService1.GetBuild(Logistics.LogisticsService.GetBuildRequest request) {
            return base.Channel.GetBuild(request);
        }
        
        public System.Data.DataSet GetBuild(string firstLetter) {
            Logistics.LogisticsService.GetBuildRequest inValue = new Logistics.LogisticsService.GetBuildRequest();
            inValue.firstLetter = firstLetter;
            Logistics.LogisticsService.GetBuildResponse retVal = ((Logistics.LogisticsService.IService1)(this)).GetBuild(inValue);
            return retVal.GetBuildResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logistics.LogisticsService.GetBuildResponse> Logistics.LogisticsService.IService1.GetBuildAsync(Logistics.LogisticsService.GetBuildRequest request) {
            return base.Channel.GetBuildAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logistics.LogisticsService.GetBuildResponse> GetBuildAsync(string firstLetter) {
            Logistics.LogisticsService.GetBuildRequest inValue = new Logistics.LogisticsService.GetBuildRequest();
            inValue.firstLetter = firstLetter;
            return ((Logistics.LogisticsService.IService1)(this)).GetBuildAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logistics.LogisticsService.GetProjectResponse Logistics.LogisticsService.IService1.GetProject(Logistics.LogisticsService.GetProjectRequest request) {
            return base.Channel.GetProject(request);
        }
        
        public System.Data.DataSet GetProject(string projectStatus, string customerName, string customerTel, string projectAddress, string projectType, string machineType, string startDate, string endDate) {
            Logistics.LogisticsService.GetProjectRequest inValue = new Logistics.LogisticsService.GetProjectRequest();
            inValue.projectStatus = projectStatus;
            inValue.customerName = customerName;
            inValue.customerTel = customerTel;
            inValue.projectAddress = projectAddress;
            inValue.projectType = projectType;
            inValue.machineType = machineType;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            Logistics.LogisticsService.GetProjectResponse retVal = ((Logistics.LogisticsService.IService1)(this)).GetProject(inValue);
            return retVal.GetProjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logistics.LogisticsService.GetProjectResponse> Logistics.LogisticsService.IService1.GetProjectAsync(Logistics.LogisticsService.GetProjectRequest request) {
            return base.Channel.GetProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logistics.LogisticsService.GetProjectResponse> GetProjectAsync(string projectStatus, string customerName, string customerTel, string projectAddress, string projectType, string machineType, string startDate, string endDate) {
            Logistics.LogisticsService.GetProjectRequest inValue = new Logistics.LogisticsService.GetProjectRequest();
            inValue.projectStatus = projectStatus;
            inValue.customerName = customerName;
            inValue.customerTel = customerTel;
            inValue.projectAddress = projectAddress;
            inValue.projectType = projectType;
            inValue.machineType = machineType;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            return ((Logistics.LogisticsService.IService1)(this)).GetProjectAsync(inValue);
        }
    }
}
